//
//  MLService.swift
//  AI-Expense-Analyzer
//
//  Created by Bianca Maciel on 23/02/26.
//

import UIKit

// MARK: - Protocols
protocol OCRService {
    /// OCR stands for 'Optical Character Recognition' which it's responsible for
    /// extract text from the image.
    /// - Parameter image: image that will be analyzed
    /// - Returns: text extracted from image
    func extractText(from image: UIImage) async throws -> String
}

protocol MLService {
    /// ML will be responsible for classifying the String and give it the proper category
    /// from Category type.
    /// - Parameter text: text extracted from image
    /// - Returns: type of expenses' category
    func classify(text: String) async throws -> Category
}

protocol InsightService {
    /// Insight will be responsible for return proper information according to extracted Expense
    /// - Parameter expenses: Expenses from all categories
    /// - Returns: Information generated by all expenses
    func generateInsight(from expenses: [Expense]) -> Insight
}


// MARK: - Errors
enum OCRServiceError: Error {
    case invalidImage
}

enum MKServiceError: Error {
    case invalidText
}

enum InsightServiceError: Error {
    case insightError
}
